### ISSUE TITLE
Date validation 

### ISSUE THREAD

**Issue by MarshallAsch** [SoorajModi/ChicagoManualOfStyle#1]
Does not validate that the date that is given as a parameter is a valid Date.  (can enter any string)

**Comment by SoorajModi** [comment]
No, it is up to the user how they want to format the date. We will not enforce a certain style.

**Comment by MarshallAsch** [comment]
Not even to permit only date strings? Since "last Tuesday" does refer to an actual date, but it is not a valid date string, even tho it could be converted into one. Permitting things can be automatically converted to a valid date format and prohibiting things like saying the date is "cat"

**Comment by SoorajModi** [comment]
I want this module to allow the user flexibility on how they choose to style their date, as opposed to enforcing a specific style onto them. If the user wants to set the date to "cat", even if its incorrect, they should be allowed to do so. I'll still consider adding it in the future, but for now its not something thats going to be enforced.
